---
- name: Configuraci贸n de Proxy Reverso para Acceso a la Aplicaci贸n Java
  hosts: ubuntu
  become: true

  tasks:
    - name: Instalar Nginx 
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Crear archivo de configuraci贸n para el proxy
      template:
        src: nginx_proxy_config.j2
        dest: /etc/nginx/sites-available/my_app
      notify:
        - Habilitar proxy
        - Reiniciar Nginx

    - name: Crear enlace simb贸lico para habilitar el proxy
      file:
        src: /etc/nginx/sites-available/my_app
        dest: /etc/nginx/sites-enabled/my_app
        state: link

  handlers:
    - name: Habilitar proxy
      command: nginx -t
      changed_when: false
    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted