---
- name: Configuración de Proxy Reverso para Acceso a la Aplicación Java
  hosts: ubuntu
  become: true

  tasks:
    
  - name: Instalar ufw
    ansible.builtin.apt:
      name: ufw
      state: present
      update_cache: true
    
  - name: Allow everything and enable UFW
    community.general.ufw:
      state: enabled
    
  - name: Habilitar ufw 80
    community.general.ufw:
      rule: allow
      port: '80'
      proto: tcp
    
  - name: Habilitar puerto 22
    community.general.ufw:
      rule: allow
      port: '22'
      proto: tcp

  - name: Instalar Apache
    ansible.builtin.apt:
      name: apache2
      state: present

  - name: Configurar sitio de proxy reverso
    ansible.builtin.copy:
      src: proxy2.conf
      dest: /etc/apache2/conf-enabled
    notify: Reiniciar Apache

  - name: Habilitar sitio de proxy reverso
    community.general.apache2_module:
      name: proxy_http
      state: present
      
    notify: Reiniciar Apache

  handlers:
    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted