---
- hosts: rocky
  user: ansible
  become: true
  vars_files: 
  - /home/ansible/TallerFebrero2024/vars/personal.yml
 
  tasks:

  - name: Instalar OpenJDK 8
    ansible.builtin.yum:
      name: java-1.8.0-openjdk-devel
      state: present
    

  - name: Crear el directorio de instalación de TomcSat
    ansible.builtin.file:
        path: /opt/tomcat
        state: directory
        mode: '0777'
        

  - name: Descargar Tomcat 8
    ansible.builtin.get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.76/bin/apache-tomcat-8.5.76.tar.gz"
        dest: /opt/apache-tomcat-8.5.76.tar.gz
  - name: Instalar tar wget
    ansible.builtin.yum:
        name: "{{ item }}"
        state: present
    loop:
    - tar
    - wget    

  - name: Extraer Tomcat
    ansible.builtin.unarchive:
       src: /opt/apache-tomcat-8.5.76.tar.gz
       dest: /opt
       remote_src: yes
       creates: /opt/apache-tomcat-8.5.76

  - name: Crear archivo de servicio systemd
    ansible.builtin.copy:
        content: |
          [Unit]
          Description=Tomcat Service
          After=syslog.target network.target

          [Service]
          Type=forking

          Environment=JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
          Environment=CATALINA_PID=/opt/apache-tomcat-8.5.76/temp/tomcat.pid
          Environment=CATALINA_HOME=/opt/apache-tomcat-8.5.76
          Environment=CATALINA_BASE=/opt/apache-tomcat-8.5.76

          ExecStart=/opt/apache-tomcat-8.5.76/bin/startup.sh
          ExecStop=/opt/apache-tomcat-8.5.76/bin/shutdown.sh

          User=root
          Group=root
          UMask=0007
          RestartSec=10
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/tomcat.service
    notify: Reload systemd
  
  - name: Iniciar Tomcat
    ansible.builtin.command:
        cmd: /opt/apache-tomcat-8.5.76/bin/startup.sh

  - name: Iniciar Tomcat
    ansible.builtin.service:
        name: tomcat
        enabled: true
        state: started
        

  
  - name: Habilitar servicio http y https
    ansible.posix.firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true

    loop: 
    - http
    - https
     

  - name: Habilitar puertos 80 y 443 
    ansible.posix.firewalld:
      port: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true

    loop: 
    - 80/tcp
    - 443/tcp    

  - name: Crear directorio /var/www/html
    ansible.builtin.file:
        path: /var/www/html
        state: directory
        mode: '0777'
        owner: ansible
        group: ansible
  - name: Instalar index.html costunizado con un tamplate
    ansible.builtin.template:
      src: /home/ansible/TallerFebrero2024/templates/index.j2
      dest: /var/www/html/index.html
      mode: '0444'
      
         
  
  

  handlers:

   - name: Reload systemd
     ansible.builtin.systemd:
        daemon_reload: yes

